# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_final_locals
    - always_declare_return_types
    - avoid_print
    - prefer_relative_imports: false
    - sort_child_properties_last
    - unawaited_futures
    - unsafe_html: false

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
